<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/scottbowles/Dev/threlte/static/models/BlenderPlanet.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Planet: THREE.Mesh
      Clouds: THREE.Mesh
      Atmosphere: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
      ['Material.002']: THREE.MeshStandardMaterial
      ['Material.003']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/BlenderPlanet.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Planet.geometry} material={gltf.materials.Material} />
    <T.Mesh geometry={gltf.nodes.Clouds.geometry} material={gltf.materials['Material.002']} scale={1.04} />
    <T.Mesh geometry={gltf.nodes.Atmosphere.geometry} material={gltf.materials['Material.003']} scale={1.15} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
