<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/scottbowles/Dev/threlte/static/models/GreenPlanet1k.glb --root /models/ --types --printwidth 120 --precision 2
Author: jimmyn64 (https://sketchfab.com/jimmyn64)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/green-planet-965dcf47e69e4c139741598162b147cf
Title: Green Planet
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Planet Rotation'
  type GLTFResult = {
    nodes: {
      Object_12: THREE.SkinnedMesh
      Object_14: THREE.SkinnedMesh
      QonoS_Atmosphere_Atmosphere_0: THREE.Mesh
      _rootJoint: THREE.Bone
    }
    materials: {
      Ground: THREE.MeshPhysicalMaterial
      Clouds: THREE.MeshStandardMaterial
      Atmosphere: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/GreenPlanet1k.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.1}>
        <T.Group name="25edeba3600546819ff876beba6912d6fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="PlanetAxis" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <T.Group name="Object_5">
                  <T is={gltf.nodes._rootJoint} />
                  <T.Group name="Object_11" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                  <T.Group name="Object_13" rotation={[-Math.PI / 2, 0, 0]} scale={100.5} />
                  <T.SkinnedMesh
                    name="Object_12"
                    geometry={gltf.nodes.Object_12.geometry}
                    material={gltf.materials.Ground}
                    skeleton={gltf.nodes.Object_12.skeleton}
                  />
                  <T.SkinnedMesh
                    name="Object_14"
                    geometry={gltf.nodes.Object_14.geometry}
                    material={gltf.materials.Clouds}
                    skeleton={gltf.nodes.Object_14.skeleton}
                  />
                </T.Group>
              </T.Group>
              <T.Group name="QonoS_Ground" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              <T.Group name="QonoS_Clouds" rotation={[-Math.PI / 2, 0, 0]} scale={100.5} />
              <T.Group name="QonoS_Atmosphere" rotation={[-Math.PI / 2, 0, 0]} scale={105.89}>
                <T.Mesh
                  name="QonoS_Atmosphere_Atmosphere_0"
                  geometry={gltf.nodes.QonoS_Atmosphere_Atmosphere_0.geometry}
                  material={gltf.materials.Atmosphere}
                />
              </T.Group>
              <T.Group name="Lamp" position={[407.62, 590.39, -100.55]} rotation={[1.89, 0.88, -2.05]} scale={100}>
                <T.Group name="Object_20" rotation={[Math.PI / 2, 0, 0]}>
                  <T.Group name="Object_21" />
                </T.Group>
              </T.Group>
              <T.Group name="Camera" position={[748.11, 534.37, 650.76]} rotation={[Math.PI, 0.76, 2.68]} scale={100}>
                <T.Group name="Object_23" />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
