<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/scottbowles/Dev/threlte/static/models/LavaPlanet1k.glb --root /models/ --types --printwidth 120 --precision 2
Author: jcises (https://sketchfab.com/jcises)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/lava-planet-f266cfb9baab4f7390c08724aea78b5b
Title: lava planet
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      defaultMaterial: THREE.Mesh
    }
    materials: {
      DefaultMaterial: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/LavaPlanet1k.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group rotation={[-Math.PI / 2, 0, 0]}>
      <T.Mesh
        geometry={gltf.nodes.defaultMaterial.geometry}
        material={gltf.materials.DefaultMaterial}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
