<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/scottbowles/Dev/threlte/static/models/PurplePlanet2k.glb --root /models/ --types --printwidth 120 --precision 2
Author: Yo.Ri (https://sketchfab.com/grox777)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/purple-planet-264eb22207184fc99a5e3b1279a763b8
Title: Purple Planet
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Take 01'
  type GLTFResult = {
    nodes: {
      Clouds_0_0: THREE.Mesh
      Planet_0: THREE.Mesh
      Clouds_1_0: THREE.Mesh
    }
    materials: {
      Clouds_0: THREE.MeshStandardMaterial
      PurplePlanet: THREE.MeshStandardMaterial
      Clouds_1: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/PurplePlanet2k.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="Root">
          <T.Group name="Planet" rotation={[0, 0, Math.PI / 2]}>
            <T.Group name="Clouds_0" rotation={[0, 0, -Math.PI / 2]} scale={1.01}>
              <T.Mesh name="Clouds_0_0" geometry={gltf.nodes.Clouds_0_0.geometry} material={gltf.materials.Clouds_0} />
            </T.Group>
            <T.Mesh name="Planet_0" geometry={gltf.nodes.Planet_0.geometry} material={gltf.materials.PurplePlanet} />
          </T.Group>
          <T.Group name="Clouds_1" scale={1.02}>
            <T.Mesh name="Clouds_1_0" geometry={gltf.nodes.Clouds_1_0.geometry} material={gltf.materials.Clouds_1} />
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
