<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 /Users/scottbowles/Dev/threlte/static/models/RedSun.glb --root /models/ --types --printwidth 120 --precision 2
Author: SebastianSosnowski (https://sketchfab.com/SebastianSosnowski)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sun-9ef1c68fbb944147bcfcc891d3912645
Title: Sun
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type ActionName = 'Take 001'
  type GLTFResult = {
    nodes: {
      UnstableStarCore_1_0: THREE.Mesh
      UnstableStarref_2_0: THREE.Mesh
    }
    materials: {
      material: THREE.MeshStandardMaterial
      material_1: THREE.MeshPhysicalMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/RedSun.glb')
  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Sketchfab_Scene">
      <T.Group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
        <T.Group name="3a2aaa22fb3d4b329318a980ad1bf6d1fbx" rotation={[Math.PI / 2, 0, 0]}>
          <T.Group name="Object_2">
            <T.Group name="RootNode">
              <T.Group name="UnstableStarCore" rotation={[-Math.PI / 2, 0, 0]}>
                <T.Mesh
                  name="UnstableStarCore_1_0"
                  geometry={gltf.nodes.UnstableStarCore_1_0.geometry}
                  material={gltf.materials.material}
                />
              </T.Group>
              <T.Group name="UnstableStarref" rotation={[-Math.PI / 2, 0, 0]} scale={1.01}>
                <T.Mesh
                  name="UnstableStarref_2_0"
                  geometry={gltf.nodes.UnstableStarref_2_0.geometry}
                  material={gltf.materials.material_1}
                />
              </T.Group>
            </T.Group>
          </T.Group>
        </T.Group>
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
